services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:5017:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: secure
      POSTGRES_DB: playerData
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:  
    image: adminer  
    restart: always
    ports:
      - "8080:8080"  # Map host port 8080 to container port 8080
    depends_on:
      - db  
volumes:
  db_data:
