"""image names are now unique

Revision ID: 274a2d26c03c
Revises: 3c401e9ccd08
Create Date: 2025-03-09 04:21:00.948312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274a2d26c03c'
down_revision = '3c401e9ccd08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
