"""Added date and status for posts

Revision ID: 2cd1c67779d7
Revises: 9b8d803a2ead
Create Date: 2025-03-20 19:57:42.269933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd1c67779d7'
down_revision = '9b8d803a2ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('pending_status')

    # ### end Alembic commands ###
