"""made image field not uniqe que fo

Revision ID: 84ddec2c7b8c
Revises: 72a41437af4b
Create Date: 2025-03-09 04:54:45.993330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84ddec2c7b8c'
down_revision = '72a41437af4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_constraint('image_image_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.create_unique_constraint('image_image_key', ['image'])

    # ### end Alembic commands ###
