"""Added to a post object if they'd like to schedule the post

Revision ID: fbb24e431097
Revises: 2cd1c67779d7
Create Date: 2025-03-20 20:05:53.315776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb24e431097'
down_revision = '2cd1c67779d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('scheduled')

    # ### end Alembic commands ###
